apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifscone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifscone
  template:
    metadata:
      labels:
        app: lifscone
    spec:
      containers:
      - image: okteto.dev/lifscone:latest
        name: lifscone
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d5939d0c-cf3a-41c8-8e20-f6fd1c374ec3"
        - name: Vless_Path
          value: "/vl5ghdjfth"
        - name: Vmess_UUID
          value: "d5939d0c-cf3a-41c8-8e20-f6fd1c374ec3"
        - name: Vmess_Path
          value: "/vm6srgdhd"
        - name: Share_Path
          value: "/v2link"
